Repository thoth-station/ansible-role-core-templates, pull requests merged in 2019-09, with the labels that each got.

#2 Add kebechet files
  tasks/main.yml
Labels: approved, size/XS

#4 add kebechet secret
  tasks/main.yml
Labels: approved, size/XS

#3 using oc apply for idempotence
  tasks/main.yml
Labels: size/S

#5 Moved all the template creation tasks from thoth-ops
  tasks/main.yml
Labels: approved, size/M
